# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "00:00"
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    groups:
      production:
        dependency-type: production
        update-types:
          - patch
          - minor
      development:
        dependency-type: development
        update-types:
          - patch
          - minor
